# Workflow zum automatischen Löschen der Exoscale Infrastruktur

name: Destroy Infrastructure


# Workflow wird manuell in GitHub gestartet
on:
  workflow_dispatch:


jobs:

  destroy:

    runs-on: ubuntu-latest


    steps:

      # Repository herunterladen
      - name: Checkout Repository
        uses: actions/checkout@v4


      # OpenTofu installieren
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1


      # OpenTofu initialisieren
      - name: Init
        working-directory: Brica_Ebin/Abgabe_2_070626/terraform
        run: tofu init


      # Infrastruktur löschen
      - name: Destroy
        working-directory: Brica_Ebin/Abgabe_2_070626/terraform

        env:
          TF_VAR_exoscale_key: ${{ secrets.EXOSCALE_API_KEY }}
          TF_VAR_exoscale_secret: ${{ secrets.EXOSCALE_API_SECRET }}

        run: tofu destroy -auto-approve