name: Deploy Exoscale Infrastrcture

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    env:
      EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
      EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Init OpenTofu
        run: tofu init

      - name: Validate configuration
        run: tofu validate

      - name: Create execution plan
        run: tofu plan

      - name: Apply infrastructure
        run: tofu apply -auto-approve
