name: Alexandra Riegler - Terraform Exoscale Deploy
#
on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Riegler_Alexandra/Abgabe_2_260603/terraform

    env:
      TF_VAR_exoscale_api_key: ${{ secrets.EXOSCALE_API_KEY }}
      TF_VAR_exoscale_api_secret: ${{ secrets.EXOSCALE_API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
 