name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'destroy' to confirm"
        required: true
        default: ""

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.8.0"

      - name: Download Terraform state
        uses: dawidd6/action-download-artifact@v6
        with:
          name: tfstate
          path: Edison_Blakaj/Abgabe_2_260517/terraform/

      - name: Init
        working-directory: Edison_Blakaj/Abgabe_2_260517/terraform
        env:
          EXOSCALE_API_KEY:    ${{ secrets.EXOSCALE_API_KEY }}
          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
        run: tofu init

      - name: Destroy
        working-directory: Edison_Blakaj/Abgabe_2_260517/terraform
        env:
          EXOSCALE_API_KEY:    ${{ secrets.EXOSCALE_API_KEY }}
          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
        run: tofu destroy -auto-approve
