name: "Destroy Infrastructure"

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Exoscale CLI
        run: |
          curl -sL https://github.com/exoscale/cli/releases/latest/download/exo_linux_amd64.tar.gz | tar -xz
          sudo mv exo /usr/local/bin/exo

      - name: Delete VM and Security Group
        env:
          EXOSCALE_API_KEY:    ${{ secrets.EXOSCALE_API_KEY }}
          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
        run: |
          exo compute instance delete blakaj-vminfo --zone at-vie-1 --force
          exo compute security-group delete blakaj-vminfo-sg --force
