name: "Buketits Deploy Infrastructure"

on: workflow_dispatch
jobs:
  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Buketits_David/Abgabe_2_Exoscale

    env:
      EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
      EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
    
      TF_STATE_PATH: ./Buketits_David/Abgabe_2_Exoscale/terraform.tfstate


      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init


      - name: Terraform Plan
        run: terraform plan
          

      - name: Terraform Apply
        # -auto-approve ist wichtig, da in der Pipeline keine manuelle Eingabe von "yes" möglich ist
        run: terraform apply -auto-approve 

      - name: Commit Terraform state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git status
          git add terraform.tfstate terraform.tfstate.backup || true
          
          git commit -m "Update Terraform state" || echo "No state changes to commit"
          git push
