name: Delete Exoscale Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Blazovich_Fabian/Abgabe_2_260603

    env:
      TF_VAR_exoscale_key: ${{ secrets.EXOSCALE_API_KEY }}
      TF_VAR_exoscale_secret: ${{ secrets.EXOSCALE_API_SECRET }}
      TF_WORKING_DIR: ./Blazovich_Fabian/Abgabe_2_260603
      TF_WORKFLOW_NAME: fblazovich-create-infra.yml

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Download Terraform State
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ env.TF_WORKFLOW_NAME }}
          name: fblazovich-tofu-state
          path: ${{ env.TF_WORKING_DIR }}
          search_artifacts: true

      - name: Initialize OpenTofu
        run: tofu init

      - name: Validate OpenTofu configuration
        run: tofu validate

      - name: Destroy OpenTofu infrastructure
        run: tofu destroy -auto-approve