name: "Destroy Infrastructure"
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      # Securely pulled from the Secrets Vault
      TF_VAR_exoscale_api_key: ${{ secrets.EXOSCALE_API_KEY }}
      TF_VAR_exoscale_api_secret: ${{ secrets.EXOSCALE_API_SECRET }}

      # Static path constants — update here if the folder structure changes
      TF_WORKING_DIR: ./Gruenwald_Georg/Abgabe_2_260516
      TF_WORKFLOW_NAME: gruenwald_deploy.yml
      
      # Fix for the Node.js 20 deprecation warning
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      # Retrieve the state file from the last Deploy run
      - name: Download Terraform State
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ env.TF_WORKFLOW_NAME }} # Tell it exactly which workflow created the artifact
          name: tofu-state
          path: ${{ env.TF_WORKING_DIR }}/ # Must end with a slash!
          search_artifacts: true
      
      # Initializes providers from the downloaded state file and tears down all provisioned infrastructure
      - name: Initialize & Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tofu init
          tofu destroy -auto-approve
