name: "Reinberg Deploy Infrastructure"
on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Sagt GitHub Actions, dass alle folgenden 'run' Befehle in diesem Ordner starten sollen
    defaults:
      run:
        working-directory: ./Reinberg-Leibel_Albert/Abgabe_2_260606

    env:
      # Securely pulled from the Secrets Vault
      TF_VAR_exoscale_api_key: ${{ secrets.EXOSCALE_API_KEY }}
      TF_VAR_exoscale_api_secret: ${{ secrets.EXOSCALE_API_SECRET }}

      # Falls back to false if the GitHub variable is empty or does not exist
      #TF_VAR_acme_staging: ${{ vars.ACME_STAGING || 'false' }}
      
      # Fix for the Node.js 20 deprecation warning
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve 